<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>KFM Companion</AssemblyName>
    <AssemblyTitle>KFM Companion</AssemblyTitle>
    <Product>KFM Companion</Product>
    <Company>Gibbed</Company>
    <Authors>Gibbed</Authors>
    <Description>KFM Companion</Description>
    <Copyright>Copyright © Gibbed 2019</Copyright>
  </PropertyGroup>
  <PropertyGroup>
    <Version>7.0.0</Version>
    <AssemblyVersion>7.0.0.0</AssemblyVersion>
    <FileVersion>7.0.3.0</FileVersion>
  </PropertyGroup>
  <PropertyGroup>
    <ApplicationIcon>kf.ico</ApplicationIcon>
    <ApplicationManifest>app.manifest</ApplicationManifest>
  </PropertyGroup>
  <PropertyGroup>
    <RepositoryUrl>https://github.com/gibbed/SteamAchievementManager/</RepositoryUrl>
    <RepositoryType>Git</RepositoryType>
  </PropertyGroup>
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net48</TargetFramework>
    <LangVersion>9.0</LangVersion>
    <Platforms>x86</Platforms>
    <PlatformTarget>x86</PlatformTarget>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <UseWindowsForms>true</UseWindowsForms>
    <DebugType>none</DebugType>
    <DebugSymbols>false</DebugSymbols>
    <GenerateSupportedRuntime>false</GenerateSupportedRuntime>
    <AutoGenerateBindingRedirects>false</AutoGenerateBindingRedirects>
    <GenerateBindingRedirectsOutputType>false</GenerateBindingRedirectsOutputType>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|x86' ">
    <OutputPath>..\bin\</OutputPath>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|x86' ">
    <OutputPath>..\upload\</OutputPath>
    <UseVSHostingProcess>false</UseVSHostingProcess>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\SAM.API\SAM.API.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Costura.Fody" Version="5.7.0" PrivateAssets="all" ExcludeAssets="runtime" />
    <PackageReference Include="Fody" Version="6.8.2" PrivateAssets="all" ExcludeAssets="runtime" />
  </ItemGroup>
  <ItemGroup>
    <UpToDateCheckInput Include="kf.ico" />
    <None Remove="kf.ico" />
    <EmbeddedResource Include="kf.ico" />
  </ItemGroup>
  <Target Name="SingleFileOutput" AfterTargets="Build">
    <ItemGroup>
      <ExtraOutput Include="$(OutputPath)*.dll" />
      <ExtraOutput Include="$(OutputPath)*.pdb" />
      <ExtraOutput Include="$(OutputPath)*.xml" />
      <ExtraOutput Include="$(OutputPath)*.exe.config" />
      <ExtraOutput Include="$(OutputPath)kf.ico" />
    </ItemGroup>
    <Delete Files="@(ExtraOutput)" TreatErrorsAsWarnings="true" />
  </Target>
</Project>
